import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideMenuBar from "./components/SideMenuBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TaskGen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Sidebar */}
        <main className="flex">
          <aside className="hidden md:block w-2/12 h-screen sticky top-0"><SideMenuBar/></aside>
          <main className="w-10/12 bg-gradient-to-br from-zinc-600 via-zinc-700 to-zinc-800 p-5 h-800">{children}</main>
        </main>
      </body>
    </html>
  );
}
