import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideMenuBar from "../components/SideMenuBar";
import Header from "../components/Header";
import UserProvider from "@/context/userContext/UserProvider";
import TaskProvider from "@/context/taskContext/TaskProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TaskGrid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/taskLogo.svg" sizes="any" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
        <main className="flex">
          <aside className="hidden md:block lg:w-2/12 w-3/12 h-screen sticky top-0 bg-gray-900"><SideMenuBar/></aside>
          <div className="lg:w-10/12 bg-zinc-950 w-full min-h-screen">
            <Header/>
            <TaskProvider>
            <div className="p-5">{children}</div>
            </TaskProvider>
          </div>
          <ToastContainer position="top-right" autoClose={5000} />
        </main>
        </UserProvider>
      </body>
    </html>
  );
}
